development:
  adapter: mysql2
  encoding: utf8
  database: hotspot_dev
  username: debian-sys-maint
  password: TThoEfMEJBMhgQnG
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: hotspot_test
  username: debian-sys-maint
  password: TThoEfMEJBMhgQnG
  host: 127.0.0.1
  port: 3306

